### ISSUE TITLE
whisperx Fails transcription with “Could not load library libcudnn_ops_infer.so.8:cannot open shared object file: No such file or directory*”

### ISSUE THREAD

**Issue by sijitang** [m-bain/whisperX#1027]
Using whisperx on google colab
Installed newest dev whisperx using:

!pip install git+https://github.com/m-bain/whisperx.git
...

whisperx /content/htdemucs_ft/7xCxpfERepU/enhanced_vocals.wav --verbose True --print_progress True --model large-v3 --device cuda --batch_size 16 --chunk_size 30 --vad_onset 0.500 --vad_offset 0.363 --vad_method pyannote --language de --compute_type float16 --output_dir .  --align_model WAV2VEC2_ASR_LARGE_LV60K_960H

/usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.11/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from torchvision.io, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have libjpeg or libpng installed before building torchvision from source?
  warn(
2025-01-29 23:13:45.762227: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable TF_ENABLE_ONEDNN_OPTS=0.
2025-01-29 23:13:45.781163: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738192425.804872    6091 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738192425.811846    6091 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-29 23:13:45.834760: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.11/dist-packages/torchvision/datapoints/__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
/usr/local/lib/python3.11/dist-packages/torchvision/transforms/v2/__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
INFO:speechbrain.utils.quirks:Applied quirks (see speechbrain.utils.quirks): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the SB_DISABLE_QUIRKS environment (comma-separated list): []
model.bin:   0% 0.00/3.09G [00:00<?, ?B/s]
vocabulary.json:   0% 0.00/1.07M [00:00<?, ?B/s]

config.json: 100% 2.39k/2.39k [00:00<00:00, 19.6MB/s]

preprocessor_config.json: 100% 340/340 [00:00<00:00, 3.09MB/s]

tokenizer.json:   0% 0.00/2.48M [00:00<?, ?B/s]
vocabulary.json: 100% 1.07M/1.07M [00:00<00:00, 7.80MB/s]
model.bin:   0% 10.5M/3.09G [00:00<01:16, 40.3MB/s]

tokenizer.json: 100% 2.48M/2.48M [00:00<00:00, 9.26MB/s]
model.bin: 100% 3.09G/3.09G [01:12<00:00, 42.4MB/s]
>>Performing voice activity detection using Pyannote...
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.5.0.post0. To apply the upgrade to your files permanently, run python -m pytorch_lightning.utilities.upgrade_checkpoint ../usr/local/lib/python3.11/dist-packages/whisperx/assets/pytorch_model.bin
Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.6.0+cu124. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
/usr/local/lib/python3.11/dist-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

  warnings.warn(
**Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory**

<details>
<summary>pip list</summary>

```plaintext
Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.2.1
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.11
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.19
albumentations                     1.4.20
ale-py                             0.10.1
alembic                            1.14.1
altair                             5.5.0
annotated-types                    0.7.0
antlr4-python3-runtime             4.9.3
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
asteroid-filterbanks               0.4.0
astropy                            6.1.7
astropy-iers-data                  0.2025.1.27.0.32.44
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread                          3.0.1
autograd                           1.7.0
av                                 14.1.0
babel                              2.16.0
backcall                           0.2.0
beautifulsoup4                     4.12.3
bigframes                          1.33.0
bigquery-magics                    0.5.0
bleach                             6.2.0
blinker                            1.9.0
blis                               0.7.11
blosc2                             3.0.0
bokeh                              3.6.2
Bottleneck                         1.4.2
bqplot                             0.12.44
branca                             0.8.1
CacheControl                       0.14.2
cachetools                         5.5.1
catalogue                          2.0.10
certifi                            2024.12.14
cffi                               1.17.1
chardet                            5.2.0
charset-normalizer                 3.4.1
chex                               0.1.88
clarabel                           0.9.0
click                              8.1.8
cloudpathlib                       0.20.0
cloudpickle                        3.1.1
cmake                              3.31.4
cmdstanpy                          1.2.5
colorcet                           3.1.0
coloredlogs                        15.0.1
colorlog                           6.9.0
colorlover                         0.3.0
colour                             0.1.5
community                          1.0.0b1
confection                         0.1.5
cons                               0.4.6
contourpy                          1.3.1
cramjam                            2.9.1
cryptography                       43.0.3
ctranslate2                        4.4.0
cuda-python                        12.6.0
cudf-cu12                          24.12.0
cufflinks                          0.17.3
cupy-cuda12x                       13.3.0
cvxopt                             1.3.2
cvxpy                              1.6.0
cycler                             0.12.1
cyipopt                            1.5.0
cymem                              2.0.11
Cython                             3.0.11
dask                               2024.10.0
datascience                        0.17.6
db-dtypes                          1.4.0
dbus-python                        1.2.18
debugpy                            1.8.0
decorator                          4.4.2
defusedxml                         0.7.1
demucs                             4.1.0a2
Deprecated                         1.2.18
diffusers                          0.32.2
distro                             1.9.0
dlib                               19.24.2
dm-tree                            0.1.8
docker-pycreds                     0.4.0
docopt                             0.6.2
docstring_parser                   0.16
docutils                           0.21.2
dopamine_rl                        4.1.2
dora_search                        0.1.12
duckdb                             1.1.3
earthengine-api                    1.4.6
easydict                           1.13
editdistance                       0.8.1
eerepr                             0.1.0
einops                             0.8.0
en-core-web-sm                     3.7.1
entrypoints                        0.4
et_xmlfile                         2.0.0
etils                              1.11.0
etuples                            0.3.9
eval_type_backport                 0.2.2
Farama-Notifications               0.0.4
fastai                             2.7.18
fastcore                           1.7.28
fastdownload                       0.0.7
faster-whisper                     1.1.0
fastjsonschema                     2.21.1
fastprogress                       1.0.3
fastrlock                          0.8.3
filelock                           3.17.0
firebase-admin                     6.6.0
Flask                              3.1.0
flatbuffers                        25.1.24
flax                               0.10.2
folium                             0.19.4
fonttools                          4.55.6
frozendict                         2.4.6
frozenlist                         1.5.0
fsspec                             2024.10.0
future                             1.0.0
gast                               0.6.0
gcsfs                              2024.10.0
GDAL                               3.6.4
gdown                              5.2.0
geemap                             0.35.1
gensim                             4.3.3
geocoder                           1.38.1
geographiclib                      2.0
geopandas                          1.0.1
geopy                              2.4.1
gin-config                         0.5.0
gitdb                              4.0.12
GitPython                          3.1.44
glob2                              0.7
google                             2.0.3
google-ai-generativelanguage       0.6.15
google-api-core                    2.19.2
google-api-python-client           2.155.0
google-auth                        2.27.0
google-auth-httplib2               0.2.0
google-auth-oauthlib               1.2.1
google-cloud-aiplatform            1.74.0
google-cloud-bigquery              3.25.0
google-cloud-bigquery-connection   1.17.0
google-cloud-bigquery-storage      2.27.0
google-cloud-bigtable              2.28.1
google-cloud-core                  2.4.1
google-cloud-datastore             2.20.2
google-cloud-firestore             2.19.0
google-cloud-functions             1.19.0
google-cloud-iam                   2.17.0
google-cloud-language              2.16.0
google-cloud-pubsub                2.25.0
google-cloud-resource-manager      1.14.0
google-cloud-spanner               3.51.0
google-cloud-storage               2.19.0
google-cloud-translate             3.19.0
google-colab                       1.0.0
google-crc32c                      1.6.0
google-genai                       0.3.0
google-generativeai                0.8.4
google-pasta                       0.2.0
google-resumable-media             2.7.2
googleapis-common-protos           1.66.0
googledrivedownloader              0.4
graphviz                           0.20.3
greenlet                           3.1.1
grpc-google-iam-v1                 0.14.0
grpc-interceptor                   0.15.4
grpcio                             1.70.0
grpcio-status                      1.62.3
gspread                            6.1.4
gspread-dataframe                  4.0.0
gym                                0.25.2
gym-notices                        0.0.8
gymnasium                          1.0.0
h11                                0.14.0
h5netcdf                           1.5.0
h5py                               3.12.1
highspy                            1.9.0
holidays                           0.65
holoviews                          1.20.0
html5lib                           1.1
httpcore                           1.0.7
httpimport                         1.4.0
httplib2                           0.22.0
httpx                              0.28.1
huggingface-hub                    0.27.1
humanfriendly                      10.0
humanize                           4.11.0
hyperopt                           0.2.7
HyperPyYAML                        1.2.2
ibis-framework                     9.2.0
idna                               3.10
imageio                            2.36.1
imageio-ffmpeg                     0.6.0
imagesize                          1.4.1
imbalanced-learn                   0.13.0
imgaug                             0.4.0
immutabledict                      4.2.1
importlib_metadata                 8.6.1
importlib_resources                6.5.2
imutils                            0.5.4
inflect                            7.5.0
iniconfig                          2.0.0
intel-cmplr-lib-ur                 2025.0.4
intel-openmp                       2025.0.4
ipyevents                          2.0.2
ipyfilechooser                     0.6.0
ipykernel                          5.5.6
ipyleaflet                         0.19.2
ipyparallel                        8.8.0
ipython                            7.34.0
ipython-genutils                   0.2.0
ipython-sql                        0.5.0
ipytree                            0.2.2
ipywidgets                         7.7.1
itsdangerous                       2.2.0
jax                                0.4.33
jax-cuda12-pjrt                    0.4.33
jax-cuda12-plugin                  0.4.33
jaxlib                             0.4.33
jeepney                            0.7.1
jellyfish                          1.1.0
jieba                              0.42.1
Jinja2                             3.1.5
jiter                              0.8.2
joblib                             1.4.2
jsonpatch                          1.33
jsonpickle                         4.0.1
jsonpointer                        3.0.0
jsonschema                         4.23.0
jsonschema-specifications          2024.10.1
julius                             0.2.7
jupyter-client                     6.1.12
jupyter-console                    6.1.0
jupyter_core                       5.7.2
jupyter-leaflet                    0.19.2
jupyter-server                     1.24.0
jupyterlab_pygments                0.3.0
jupyterlab_widgets                 3.0.13
kaggle                             1.6.17
kagglehub                          0.3.6
keras                              3.8.0
keyring                            23.5.0
kiwisolver                         1.4.8
lameenc                            1.8.1
langchain                          0.3.15
langchain-core                     0.3.31
langchain-text-splitters           0.3.5
langcodes                          3.5.0
langsmith                          0.3.1
language_data                      1.3.0
launchpadlib                       1.10.16
lazr.restfulclient                 0.14.4
lazr.uri                           1.0.6
lazy_loader                        0.4
libclang                           18.1.1
libcudf-cu12                       24.12.0
libkvikio-cu12                     24.12.1
librosa                            0.10.2.post1
lightgbm                           4.5.0
lightning                          2.5.0.post0
lightning-utilities                0.11.9
linkify-it-py                      2.0.3
lit                                18.1.8
llvmlite                           0.43.0
locket                             1.0.0
logical-unification                0.4.6
lxml                               5.3.0
Mako                               1.3.8
marisa-trie                        1.2.1
Markdown                           3.7
markdown-it-py                     3.0.0
MarkupSafe                         3.0.2
matplotlib                         3.10.0
matplotlib-inline                  0.1.7
matplotlib-venn                    1.1.1
mdit-py-plugins                    0.4.2
mdurl                              0.1.2
miniKanren                         1.0.3
missingno                          0.5.2
mistune                            3.1.0
mizani                             0.13.1
mkl                                2025.0.1
ml-dtypes                          0.4.1
mlxtend                            0.23.4
more-itertools                     10.5.0
moviepy                            1.0.3
mpmath                             1.3.0
msgpack                            1.1.0
multidict                          6.1.0
multipledispatch                   1.0.0
multitasking                       0.0.11
murmurhash                         1.0.12
music21                            9.3.0
namex                              0.0.8
narwhals                           1.24.0
natsort                            8.4.0
nbclassic                          1.2.0
nbclient                           0.10.2
nbconvert                          7.16.5
nbformat                           5.10.4
ndindex                            1.9.2
nest-asyncio                       1.6.0
networkx                           3.4.2
nibabel                            5.3.2
nltk                               3.9.1
notebook                           6.5.5
notebook_shim                      0.2.4
numba                              0.60.0
numba-cuda                         0.0.17.1
numexpr                            2.10.2
numpy                              1.26.4
nvidia-cublas-cu12                 12.4.5.8
nvidia-cuda-cupti-cu12             12.4.127
nvidia-cuda-nvcc-cu12              12.5.82
nvidia-cuda-nvrtc-cu12             12.4.127
nvidia-cuda-runtime-cu12           12.4.127
nvidia-cudnn-cu12                  9.1.0.70
nvidia-cufft-cu12                  11.2.1.3
nvidia-curand-cu12                 10.3.5.147
nvidia-cusolver-cu12               11.6.1.9
nvidia-cusparse-cu12               12.3.1.170
nvidia-cusparselt-cu12             0.6.2
nvidia-nccl-cu12                   2.21.5
nvidia-nvcomp-cu12                 4.1.0.6
nvidia-nvjitlink-cu12              12.4.127
nvidia-nvtx-cu12                   12.4.127
nvtx                               0.2.10
nx-cugraph-cu12                    24.12.0
oauth2client                       4.1.3
oauthlib                           3.2.2
omegaconf                          2.3.0
onnxruntime                        1.20.1
openai                             1.59.9
opencv-contrib-python              4.10.0.84
opencv-python                      4.10.0.84
opencv-python-headless             4.11.0.86
openpyxl                           3.1.5
opentelemetry-api                  1.16.0
opentelemetry-sdk                  1.16.0
opentelemetry-semantic-conventions 0.37b0
openunmix                          1.3.0
opt_einsum                         3.4.0
optax                              0.2.4
optree                             0.14.0
optuna                             4.2.0
orbax-checkpoint                   0.6.4
orjson                             3.10.15
osqp                               0.6.7.post3
packaging                          24.2
pandas                             2.2.2
pandas-datareader                  0.10.0
pandas-gbq                         0.26.1
pandas-stubs                       2.2.2.240909
pandocfilters                      1.5.1
panel                              1.6.0
param                              2.2.0
parso                              0.8.4
parsy                              2.1
partd                              1.4.2
pathlib                            1.0.1
patsy                              1.0.1
peewee                             3.17.8
peft                               0.14.0
pexpect                            4.9.0
pickleshare                        0.7.5
pillow                             11.1.0
pip                                24.1.2
platformdirs                       4.3.6
plotly                             5.24.1
plotnine                           0.14.5
pluggy                             1.5.0
ply                                3.11
polars                             1.9.0
pooch                              1.8.2
portpicker                         1.5.2
preshed                            3.0.9
prettytable                        3.13.0
primePy                            1.3
proglog                            0.1.10
progressbar2                       4.5.0
prometheus_client                  0.21.1
promise                            2.3
prompt_toolkit                     3.0.50
propcache                          0.2.1
prophet                            1.1.6
proto-plus                         1.25.0
protobuf                           4.25.6
psutil                             5.9.5
psycopg2                           2.9.10
ptyprocess                         0.7.0
py-cpuinfo                         9.0.0
py4j                               0.10.9.7
pyannote.audio                     3.3.2
pyannote.core                      5.0.0
pyannote.database                  5.1.3
pyannote.metrics                   3.2.1
pyannote.pipeline                  3.0.1
pyarrow                            17.0.0
pyasn1                             0.6.1
pyasn1_modules                     0.4.1
pycocotools                        2.0.8
pycparser                          2.22
pydantic                           2.10.6
pydantic_core                      2.27.2
pydata-google-auth                 1.9.1
pydot                              3.0.4
pydotplus                          2.0.2
PyDrive                            1.3.1
PyDrive2                           1.21.3
pyerfa                             2.0.1.5
pygame                             2.6.1
pygit2                             1.16.0
Pygments                           2.18.0
PyGObject                          3.42.1
PyJWT                              2.10.1
pylibcudf-cu12                     24.12.0
pylibcugraph-cu12                  24.12.0
pylibraft-cu12                     24.12.0
pymc                               5.19.1
pymystem3                          0.2.0
pynvjitlink-cu12                   0.4.0
pyogrio                            0.10.0
Pyomo                              6.8.2
PyOpenGL                           3.1.9
pyOpenSSL                          24.2.1
pyparsing                          3.2.1
pyperclip                          1.9.0
pyproj                             3.7.0
pyshp                              2.3.1
PySocks                            1.7.1
pyspark                            3.5.4
pytensor                           2.26.4
pytest                             8.3.4
python-apt                         0.0.0
python-box                         7.3.2
python-dateutil                    2.8.2
python-louvain                     0.16
python-slugify                     8.0.4
python-snappy                      0.7.3
python-utils                       3.9.1
pytorch-lightning                  2.5.0.post0
pytorch-metric-learning            2.8.1
pytz                               2024.2
pyviz_comms                        3.0.4
PyYAML                             6.0.2
pyzmq                              24.0.1
qdldl                              0.1.7.post5
ratelim                            0.1.6
referencing                        0.36.2
regex                              2024.11.6
requests                           2.32.3
requests-oauthlib                  1.3.1
requests-toolbelt                  1.0.0
requirements-parser                0.9.0
retrying                           1.3.4
rich                               13.9.4
rmm-cu12                           24.12.1
rpds-py                            0.22.3
rpy2                               3.4.2
rsa                                4.9
ruamel.yaml                        0.18.10
ruamel.yaml.clib                   0.2.12
safetensors                        0.5.2
scikit-image                       0.25.1
scikit-learn                       1.6.1
scipy                              1.13.1
scooby                             0.10.0
scs                                3.2.7.post2
seaborn                            0.13.2
SecretStorage                      3.3.1
semver                             3.0.4
Send2Trash                         1.8.3
sentence-transformers              3.3.1
sentencepiece                      0.2.0
sentry-sdk                         2.20.0
setproctitle                       1.3.4
setuptools                         75.1.0
shap                               0.46.0
shapely                            2.0.6
shellingham                        1.5.4
simple-parsing                     0.1.7
six                                1.17.0
sklearn-compat                     0.1.3
sklearn-pandas                     2.2.0
slicer                             0.0.8
smart-open                         7.1.0
smmap                              5.0.2
sniffio                            1.3.1
snowballstemmer                    2.2.0
sortedcontainers                   2.4.0
soundfile                          0.13.1
soupsieve                          2.6
soxr                               0.5.0.post1
spacy                              3.7.5
spacy-legacy                       3.0.12
spacy-loggers                      1.0.5
spanner-graph-notebook             1.0.9
speechbrain                        1.0.2
Sphinx                             8.1.3
sphinxcontrib-applehelp            2.0.0
sphinxcontrib-devhelp              2.0.0
sphinxcontrib-htmlhelp             2.1.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               2.0.0
sphinxcontrib-serializinghtml      2.0.0
SQLAlchemy                         2.0.37
sqlglot                            25.6.1
sqlparse                           0.5.3
srsly                              2.5.1
stanio                             0.5.1
statsmodels                        0.14.4
stringzilla                        3.11.3
submitit                           1.5.2
sympy                              1.13.1
tables                             3.10.2
tabulate                           0.9.0
tbb                                2022.0.0
tcmlib                             1.2.0
tenacity                           9.0.0
tensorboard                        2.18.0
tensorboard-data-server            0.7.2
tensorboardX                       2.6.2.2
tensorflow                         2.18.0
tensorflow-datasets                4.9.7
tensorflow-hub                     0.16.1
tensorflow-io-gcs-filesystem       0.37.1
tensorflow-metadata                1.16.1
tensorflow-probability             0.24.0
tensorstore                        0.1.71
termcolor                          2.5.0
terminado                          0.18.1
text-unidecode                     1.3
textblob                           0.17.1
tf_keras                           2.18.0
tf-slim                            1.1.0
thinc                              8.2.5
threadpoolctl                      3.5.0
tifffile                           2025.1.10
timm                               1.0.14
tinycss2                           1.4.0
tokenizers                         0.21.0
toml                               0.10.2
toolz                              0.12.1
torch                              2.6.0
torch-audiomentations              0.12.0
torch_pitch_shift                  1.2.5
torchaudio                         2.6.0
torchmetrics                       1.6.1
torchsummary                       1.5.1
torchvision                        0.15.1+cu118
tornado                            6.3.3
tqdm                               4.67.1
traitlets                          5.7.1
traittypes                         0.2.1
transformers                       4.47.1
treetable                          0.2.5
triton                             3.2.0
tweepy                             4.14.0
typeguard                          4.4.1
typer                              0.15.1
types-pytz                         2024.2.0.20241221
types-setuptools                   75.8.0.20250110
typing_extensions                  4.12.2
tzdata                             2025.1
tzlocal                            5.2
uc-micro-py                        1.0.3
umf                                0.9.1
uritemplate                        4.1.1
urllib3                            2.3.0
vega-datasets                      0.9.0
wadllib                            1.3.6
wandb                              0.19.4
wasabi                             1.1.3
wcwidth                            0.2.13
weasel                             0.4.1
webcolors                          24.11.1
webencodings                       0.5.1
websocket-client                   1.8.0
websockets                         14.2
Werkzeug                           3.1.3
wheel                              0.45.1
whisperx                           3.3.1
widgetsnbextension                 3.6.10
wordcloud                          1.9.4
wrapt                              1.17.2
xarray                             2025.1.1
xarray-einstats                    0.8.0
xgboost                            2.1.3
xlrd                               2.0.1
xyzservices                        2025.1.0
yarl                               1.18.3
yellowbrick                        1.5
yfinance                           0.2.52
yt-dlp                             2025.1.26
zipp                               3.21.0
zstandard                          0.23.0
</details>

**Comment by sharanya-b2** [comment]
Facing same issue. Any quick fix for this? Our entire pipeline is stuck due to this.

**Comment by laportguy** [comment]
before installing whisperx run:

! pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121

then after installing whisperx run:
!apt-get update
!apt-get install libcudnn8=8.9.2.26-1+cuda12.1
!apt-get install libcudnn8-dev=8.9.2.26-1+cuda12.1
!python -c "import torch; torch.backends.cuda.matmul.allow_tf32 = True; torch.backends.cudnn.allow_tf32 = True"
!ln -s /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8

it fixed it for me

**Comment by spirifax** [comment]
That did it for me to

Thank you very much

**Comment by sijitang** [comment]
> Seems like Colab upgraded from CUDA 12.1 to CUDA 12.4

yes

> ! pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121

and this downgraded torch from Version: 2.5.1+cu124 to Version: 2.5.1+cu121 and also work for me . thank you,


> !ln -s /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8

this line may be not necessary. because:
ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8': File exists

**Comment by pneuly** [comment]
I'm looking for a solution to avoid downgrading CUDA to 12.1. I have not found a true solution yet, but I've found some factors that may cause errors:
- CTranslate2 and faster-whisper, which pyannote.audio depends on, conflict with each other.
- A workaround is to isolate the processes of transcription (faster-whisper) and diarization (pyannote.audio).

### If faster whisper is used alone, it works
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
from faster_whisper import WhisperModel

audio_file = "sample-0.mp3"
model_size = "tiny"

# ASR
model = WhisperModel(model_size)
segments, _ = model.transcribe(audio_file)
for segment in segments:
    print(segment.text)
```
</details>
<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Resolved 25 packages in 336ms
Prepared 6 packages in 1.73s
Installed 6 packages in 20ms
 + av==14.1.0
 + coloredlogs==15.0.1
 + ctranslate2==4.5.0
 + faster-whisper==1.1.1
 + humanfriendly==10.0
 + onnxruntime==1.20.1
 My thought, I have nobody by a beauty and will as you poured.
 Mr. Rochester has served and that so don't find simplest, and devoted to bowed, to let might in a-
```
</details>

### When pyannote.audio is installed in Colab, its dependency make torch upgrade from 2.5.1+cu124 to 2.6.0 and nvidia-cudnn-cu12 downgrade from 9.3.0.75 to 9.1.0.70. faster whisper still works.
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
from faster_whisper import WhisperModel

audio_file = "sample-0.mp3"
model_size = "tiny"

# ASR
model = WhisperModel(model_size)
segments, _ = model.transcribe(audio_file)
for segment in segments:
    print(segment.text)
```
</details>
<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Resolved 112 packages in 4.56s
Prepared 49 packages in 1m 07s
Uninstalled 13 packages in 650ms
Installed 49 packages in 404ms
 + alembic==1.14.1
 + antlr4-python3-runtime==4.9.3
 + asteroid-filterbanks==0.4.0
 + av==14.1.0
 + coloredlogs==15.0.1
 + colorlog==6.9.0
 + ctranslate2==4.5.0
 + docopt==0.6.2
 + faster-whisper==1.1.1
 + humanfriendly==10.0
 + hyperpyyaml==1.2.2
 + julius==0.2.7
 + lightning==2.5.0.post0
 + lightning-utilities==0.12.0
 + mako==1.3.9
 - nvidia-cublas-cu12==12.5.3.2
 + nvidia-cublas-cu12==12.4.5.8
 - nvidia-cuda-cupti-cu12==12.5.82
 + nvidia-cuda-cupti-cu12==12.4.127
 - nvidia-cuda-nvrtc-cu12==12.5.82
 + nvidia-cuda-nvrtc-cu12==12.4.127
 - nvidia-cuda-runtime-cu12==12.5.82
 + nvidia-cuda-runtime-cu12==12.4.127
 - nvidia-cudnn-cu12==9.3.0.75
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.2.3.61
 + nvidia-cufft-cu12==11.2.1.3
 - nvidia-curand-cu12==10.3.6.82
 + nvidia-curand-cu12==10.3.5.147
 - nvidia-cusolver-cu12==11.6.3.83
 + nvidia-cusolver-cu12==11.6.1.9
 - nvidia-cusparse-cu12==12.5.1.3
 + nvidia-cusparse-cu12==12.3.1.170
 + nvidia-cusparselt-cu12==0.6.2
 - nvidia-nvjitlink-cu12==12.5.82
 + nvidia-nvjitlink-cu12==12.4.127
 + omegaconf==2.3.0
 + onnxruntime==1.20.1
 + optuna==4.2.0
 + primepy==1.3
 + pyannote-audio==3.3.2
 + pyannote-core==5.0.0
 + pyannote-database==5.1.3
 + pyannote-metrics==3.2.1
 + pyannote-pipeline==3.0.1
 + pytorch-lightning==2.5.0.post0
 + pytorch-metric-learning==2.8.1
 + ruamel-yaml==0.18.10
 + ruamel-yaml-clib==0.2.12
 + semver==3.0.4
 + sortedcontainers==2.4.0
 + speechbrain==1.0.2
 + tensorboardx==2.6.2.2
 - torch==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torch==2.6.0
 + torch-audiomentations==0.12.0
 + torch-pitch-shift==1.2.5
 - torchaudio==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torchaudio==2.6.0
 + torchmetrics==1.6.1
 - triton==3.1.0
 + triton==3.2.0
 My thought, I have nobody by a beauty and will as you poured.
 Mr. Rochester has served and that so don't find simplest, and devoted to bowed, to let might in a-
```
</details>

### Similarly, pyannote.audio works if used alone
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
import torch
from pyannote.audio import Pipeline

audio_file = "sample-0.mp3"
model_name = "pyannote/speaker-diarization-3.1"
hugging_face_token = "YOUR_HF_TOKEN"

# Diarize
pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = pipeline.to(torch.device(device))
result = pipeline(audio_file).itertracks(yield_label=True)
for turn, _, speaker in result:
    print(f"start={turn.start:.1f}s end={turn.end:.1f}s speaker_{speaker}")
```
</details>
<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Audited 2 packages in 88ms
start=0.0s stop=3.2s speaker_SPEAKER_00
start=3.8s stop=8.5s speaker_SPEAKER_00
start=9.0s stop=10.1s speaker_SPEAKER_00
```
</details>

### However, if faster whisper is used beforehand, pyannote.audio stucks at pipeline.to(torch.device("cuda")) (RuntimeError: cuDNN error: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH)
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
import torch
from faster_whisper import WhisperModel
from pyannote.audio import Pipeline

audio_file = "sample-0.mp3"
model_size = "tiny"
model_name = "pyannote/speaker-diarization-3.1"
hugging_face_token = "YOUR_HF_TOKEN"

# ASR
model = WhisperModel(model_size)
segments, _ = model.transcribe(audio_file)
for segment in segments:
    print(segment.text)

# Diarize
pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = pipeline.to(torch.device(device)) # RuntimeError: cuDNN error: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH
result = pipeline(audio_file).itertracks(yield_label=True)
for turn, _, speaker in result:
    print(f"start={turn.start:.1f}s end={turn.end:.1f}s speaker_{speaker}")
```
</details>
<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Audited 2 packages in 144ms
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-8bfc98d2f1eb> in <cell line: 0>()
     21 pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
     22 device = "cuda" if torch.cuda.is_available() else "cpu"
---> 23 pipeline = pipeline.to(torch.device(device))
     24 result = pipeline(audio_file).itertracks(yield_label=True)
     25 for turn, _, speaker in result:

7 frames
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/rnn.py in flatten_parameters(self)
    269                     if self.proj_size > 0:
    270                         num_weights += 1
--> 271                     torch._cudnn_rnn_flatten_weight(
    272                         self._flat_weights,  # type: ignore[arg-type]
    273                         num_weights,

RuntimeError: cuDNN error: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH
```
</details>

### Similarly, if pyannote.audio is imported beforehand, faster whisper crashes.
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
import torch
from faster_whisper import WhisperModel
from pyannote.audio import Pipeline

audio_file = "sample-0.mp3"
model_size = "tiny"
model_name = "pyannote/speaker-diarization-3.1"
hugging_face_token = "YOUR_HF_TOKEN"

# Diarize
pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = pipeline.to(torch.device(device))
result = pipeline(audio_file).itertracks(yield_label=True)
for turn, _, speaker in result: # [src/libmpg123/layer3.c:INT123_do_layer3():1774] error: part2_3_length (2528) too large for available bit count (2400)
    print(f"start={turn.start:.1f}s end={turn.end:.1f}s speaker_{speaker}")

# ASR
model = WhisperModel(model_size)
segments, _ = model.transcribe(audio_file)
for segment in segments:
    print(segment.text)
```
</details>

<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Resolved 112 packages in 4.41s
Prepared 49 packages in 57.64s
Uninstalled 13 packages in 698ms
Installed 49 packages in 474ms
 + alembic==1.14.1
 + antlr4-python3-runtime==4.9.3
 + asteroid-filterbanks==0.4.0
 + av==14.1.0
 + coloredlogs==15.0.1
 + colorlog==6.9.0
 + ctranslate2==4.5.0
 + docopt==0.6.2
 + faster-whisper==1.1.1
 + humanfriendly==10.0
 + hyperpyyaml==1.2.2
 + julius==0.2.7
 + lightning==2.5.0.post0
 + lightning-utilities==0.12.0
 + mako==1.3.9
 - nvidia-cublas-cu12==12.5.3.2
 + nvidia-cublas-cu12==12.4.5.8
 - nvidia-cuda-cupti-cu12==12.5.82
 + nvidia-cuda-cupti-cu12==12.4.127
 - nvidia-cuda-nvrtc-cu12==12.5.82
 + nvidia-cuda-nvrtc-cu12==12.4.127
 - nvidia-cuda-runtime-cu12==12.5.82
 + nvidia-cuda-runtime-cu12==12.4.127
 - nvidia-cudnn-cu12==9.3.0.75
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.2.3.61
 + nvidia-cufft-cu12==11.2.1.3
 - nvidia-curand-cu12==10.3.6.82
 + nvidia-curand-cu12==10.3.5.147
 - nvidia-cusolver-cu12==11.6.3.83
 + nvidia-cusolver-cu12==11.6.1.9
 - nvidia-cusparse-cu12==12.5.1.3
 + nvidia-cusparse-cu12==12.3.1.170
 + nvidia-cusparselt-cu12==0.6.2
 - nvidia-nvjitlink-cu12==12.5.82
 + nvidia-nvjitlink-cu12==12.4.127
 + omegaconf==2.3.0
 + onnxruntime==1.20.1
 + optuna==4.2.0
 + primepy==1.3
 + pyannote-audio==3.3.2
 + pyannote-core==5.0.0
 + pyannote-database==5.1.3
 + pyannote-metrics==3.2.1
 + pyannote-pipeline==3.0.1
 + pytorch-lightning==2.5.0.post0
 + pytorch-metric-learning==2.8.1
 + ruamel-yaml==0.18.10
 + ruamel-yaml-clib==0.2.12
 + semver==3.0.4
 + sortedcontainers==2.4.0
 + speechbrain==1.0.2
 + tensorboardx==2.6.2.2
 - torch==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torch==2.6.0
 + torch-audiomentations==0.12.0
 + torch-pitch-shift==1.2.5
 - torchaudio==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torchaudio==2.6.0
 + torchmetrics==1.6.1
 - triton==3.1.0
 + triton==3.2.0
start=0.0s stop=3.2s speaker_SPEAKER_00
start=3.8s stop=8.5s speaker_SPEAKER_00
start=9.0s stop=10.1s speaker_SPEAKER_00
***crashes here
```
</details>

### Workaround: Isolate faster whisper using multiprocessing
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
import multiprocessing
import torch
from faster_whisper import WhisperModel
from pyannote.audio import Pipeline

audio_file = "sample-0.mp3"
model_size = "tiny"
model_name = "pyannote/speaker-diarization-3.1"
hugging_face_token = "YOUR_HF_TOKEN"

# ASR
def transcribe(model_size, audio_file):
    model = WhisperModel(model_size)
    segments, _ = model.transcribe(audio_file)
    for segment in segments:
        print(segment.text, flush=True)
p = multiprocessing.Process(target=transcribe, args=(model_size, audio_file))
p.start()
p.join()

# Diarize
pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = pipeline.to(torch.device(device))
result = pipeline(audio_file).itertracks(yield_label=True)
for turn, _, speaker in result:
    print(f"start={turn.start:.1f}s end={turn.end:.1f}s speaker_{speaker}")
```
</details>

<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Resolved 112 packages in 5.32s
Prepared 49 packages in 1m 13s
Uninstalled 13 packages in 674ms
Installed 49 packages in 395ms
 + alembic==1.14.1
 + antlr4-python3-runtime==4.9.3
 + asteroid-filterbanks==0.4.0
 + av==14.1.0
 + coloredlogs==15.0.1
 + colorlog==6.9.0
 + ctranslate2==4.5.0
 + docopt==0.6.2
 + faster-whisper==1.1.1
 + humanfriendly==10.0
 + hyperpyyaml==1.2.2
 + julius==0.2.7
 + lightning==2.5.0.post0
 + lightning-utilities==0.12.0
 + mako==1.3.9
 - nvidia-cublas-cu12==12.5.3.2
 + nvidia-cublas-cu12==12.4.5.8
 - nvidia-cuda-cupti-cu12==12.5.82
 + nvidia-cuda-cupti-cu12==12.4.127
 - nvidia-cuda-nvrtc-cu12==12.5.82
 + nvidia-cuda-nvrtc-cu12==12.4.127
 - nvidia-cuda-runtime-cu12==12.5.82
 + nvidia-cuda-runtime-cu12==12.4.127
 - nvidia-cudnn-cu12==9.3.0.75
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.2.3.61
 + nvidia-cufft-cu12==11.2.1.3
 - nvidia-curand-cu12==10.3.6.82
 + nvidia-curand-cu12==10.3.5.147
 - nvidia-cusolver-cu12==11.6.3.83
 + nvidia-cusolver-cu12==11.6.1.9
 - nvidia-cusparse-cu12==12.5.1.3
 + nvidia-cusparse-cu12==12.3.1.170
 + nvidia-cusparselt-cu12==0.6.2
 - nvidia-nvjitlink-cu12==12.5.82
 + nvidia-nvjitlink-cu12==12.4.127
 + omegaconf==2.3.0
 + onnxruntime==1.20.1
 + optuna==4.2.0
 + primepy==1.3
 + pyannote-audio==3.3.2
 + pyannote-core==5.0.0
 + pyannote-database==5.1.3
 + pyannote-metrics==3.2.1
 + pyannote-pipeline==3.0.1
 + pytorch-lightning==2.5.0.post0
 + pytorch-metric-learning==2.8.1
 + ruamel-yaml==0.18.10
 + ruamel-yaml-clib==0.2.12
 + semver==3.0.4
 + sortedcontainers==2.4.0
 + speechbrain==1.0.2
 + tensorboardx==2.6.2.2
 - torch==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torch==2.6.0
 + torch-audiomentations==0.12.0
 + torch-pitch-shift==1.2.5
 - torchaudio==2.5.1+cu124 (from https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp311-cp311-linux_x86_64.whl)
 + torchaudio==2.6.0
 + torchmetrics==1.6.1
 - triton==3.1.0
 + triton==3.2.0
 My thought, I have nobody by a beauty and will as you poured.
 Mr. Rochester has served and that so don't find simplest, and devoted to bowed, to let might in a-
start=0.0s end=3.2s speaker_SPEAKER_00
start=3.8s end=8.5s speaker_SPEAKER_00
start=9.0s end=10.1s speaker_SPEAKER_00
```
</details>

### Improved workaround: Upgrading torch takes long time, so avoid unnecessary upgrading.
<details><summary>Code</summary>

```
!uv pip install --system --no-progress faster-whisper pyannote.audio torchaudio==2.5.1+cu124
!curl -OL https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-0.mp3
import multiprocessing
import torch
from faster_whisper import WhisperModel
from pyannote.audio import Pipeline

audio_file = "sample-0.mp3"
model_size = "tiny"
model_name = "pyannote/speaker-diarization-3.1"
hugging_face_token = "YOUR_HF_TOKEN"

# ASR
def transcribe(model_size, audio_file):
    model = WhisperModel(model_size)
    segments, _ = model.transcribe(audio_file)
    for segment in segments:
        print(segment.text, flush=True)
p = multiprocessing.Process(target=transcribe, args=(model_size, audio_file))
p.start()
p.join()

# Diarize
pipeline = Pipeline.from_pretrained(model_name, use_auth_token=hugging_face_token)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = pipeline.to(torch.device(device))
result = pipeline(audio_file).itertracks(yield_label=True)
for turn, _, speaker in result:
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```
</details>
<details><summary>Output</summary>

```
Using Python 3.11.11 environment at /usr
Resolved 111 packages in 4.62s
Prepared 45 packages in 27.43s
Uninstalled 10 packages in 33ms
Installed 45 packages in 69ms
 + alembic==1.14.1
 + antlr4-python3-runtime==4.9.3
 + asteroid-filterbanks==0.4.0
 + av==14.1.0
 + coloredlogs==15.0.1
 + colorlog==6.9.0
 + ctranslate2==4.5.0
 + docopt==0.6.2
 + faster-whisper==1.1.1
 + humanfriendly==10.0
 + hyperpyyaml==1.2.2
 + julius==0.2.7
 + lightning==2.5.0.post0
 + lightning-utilities==0.12.0
 + mako==1.3.9
 - nvidia-cublas-cu12==12.5.3.2
 + nvidia-cublas-cu12==12.4.5.8
 - nvidia-cuda-cupti-cu12==12.5.82
 + nvidia-cuda-cupti-cu12==12.4.127
 - nvidia-cuda-nvrtc-cu12==12.5.82
 + nvidia-cuda-nvrtc-cu12==12.4.127
 - nvidia-cuda-runtime-cu12==12.5.82
 + nvidia-cuda-runtime-cu12==12.4.127
 - nvidia-cudnn-cu12==9.3.0.75
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.2.3.61
 + nvidia-cufft-cu12==11.2.1.3
 - nvidia-curand-cu12==10.3.6.82
 + nvidia-curand-cu12==10.3.5.147
 - nvidia-cusolver-cu12==11.6.3.83
 + nvidia-cusolver-cu12==11.6.1.9
 - nvidia-cusparse-cu12==12.5.1.3
 + nvidia-cusparse-cu12==12.3.1.170
 - nvidia-nvjitlink-cu12==12.5.82
 + nvidia-nvjitlink-cu12==12.4.127
 + omegaconf==2.3.0
 + onnxruntime==1.20.1
 + optuna==4.2.0
 + primepy==1.3
 + pyannote-audio==3.3.2
 + pyannote-core==5.0.0
 + pyannote-database==5.1.3
 + pyannote-metrics==3.2.1
 + pyannote-pipeline==3.0.1
 + pytorch-lightning==2.5.0.post0
 + pytorch-metric-learning==2.8.1
 + ruamel-yaml==0.18.10
 + ruamel-yaml-clib==0.2.12
 + semver==3.0.4
 + sortedcontainers==2.4.0
 + speechbrain==1.0.2
 + tensorboardx==2.6.2.2
 + torch-audiomentations==0.12.0
 + torch-pitch-shift==1.2.5
 + torchmetrics==1.6.1
 My thought, I have nobody by a beauty and will as you poured.
 Mr. Rochester has served and that so don't find simplest, and devoted to bowed, to let might in a-
start=0.0s stop=3.2s speaker_SPEAKER_00
start=3.8s stop=8.5s speaker_SPEAKER_00
start=9.0s stop=10.1s speaker_SPEAKER_00
```
</details>

**Comment by kevdawg94** [comment]
Huge! This worked for me as well. I thought my issue was related to the glibc and ctranslate2 versions and was spinning my wheels. Thank you.

> before installing whisperx run:
> 
> ! pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
> 
> then after installing whisperx run: !apt-get update !apt-get install libcudnn8=8.9.2.26-1+cuda12.1 !apt-get install libcudnn8-dev=8.9.2.26-1+cuda12.1 !python -c "import torch; torch.backends.cuda.matmul.allow_tf32 = True; torch.backends.cudnn.allow_tf32 = True" !ln -s /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
> 
> it fixed it for me

**Comment by mtfugin** [comment]
> > Seems like Colab upgraded from CUDA 12.1 to CUDA 12.4
> 
> yes
> 
> > ! pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
> > !apt-get install libcudnn8=8.9.2.26-1+cuda12.1
> > !apt-get install libcudnn8-dev=8.9.2.26-1+cuda12.1
> 
> also works for me. this downgraded torch from Version: 2.5.1+cu124 to Version: 2.5.1+cu121 and install libcudnn8 manually . thank you,
> 
> > !ln -s /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
> 
> this line may be not necessary. because: ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8': File exists

Thanks Man, it worked!

**Comment by mtfugin** [comment]
> before installing whisperx run:
> 
> ! pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
> 
> then after installing whisperx run: !apt-get update !apt-get install libcudnn8=8.9.2.26-1+cuda12.1 !apt-get install libcudnn8-dev=8.9.2.26-1+cuda12.1 !python -c "import torch; torch.backends.cuda.matmul.allow_tf32 = True; torch.backends.cudnn.allow_tf32 = True" !ln -s /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
> 
> it fixed it for me

Thanks Man, it worked!

**Comment by dgarciarieckhof** [comment]
> I'm looking for a solution to avoid downgrading CUDA to 12.1. I have not found a true solution yet, but I've found some factors that may cause errors:
> 
> * CTranslate2 and pyannote.audio conflict with each other.
> * A workaround is to isolate the processes of transcription (CTranslate2) and diarization (pyannote.audio).
> 
> ### If CTranslate2 is used alone, it works
> Code
> Output
> ### When pyannote.audio is installed in Colab, its dependency make torch upgrade from 2.5.1+cu124 to 2.6.0 and nvidia-cudnn-cu12 downgrade from 9.3.0.75 to 9.1.0.70. CTranslate2 still works.
> Code
> Output
> ### Similarly, pyannote.audio works if used alone
> Code
> Output
> ### However, if CTranslate2 is used beforehand, pyannote.audio stucks at pipeline.to(torch.device("cuda")) (RuntimeError: cuDNN error: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH)
> Code
> Output
> ### Similarly, if pyannote.audio is imported beforehand, CTranslate2 crashes.
> Code
> Output
> ### Workaround: Isolate CTranslate2 process using multiprocessing
> Code
> Output
> ### Improved workaround: Upgrading torch takes long time, so avoid unnecessary upgrading.
> Code
> Output

You deserve a place in heaven, thanks! after two days trying workarounds finally it worked, didn't want to downgrade my cuda just for this lib.

**Comment by mtfugin** [comment]
> I'm looking for a solution to avoid downgrading CUDA to 12.1. I have not found a true solution yet, but I've found some factors that may cause errors:
> 
> * CTranslate2 and pyannote.audio conflict with each other.
> * A workaround is to isolate the processes of transcription (CTranslate2) and diarization (pyannote.audio).
> 
> ### If CTranslate2 is used alone, it works
> Code
> Output
> ### When pyannote.audio is installed in Colab, its dependency make torch upgrade from 2.5.1+cu124 to 2.6.0 and nvidia-cudnn-cu12 downgrade from 9.3.0.75 to 9.1.0.70. CTranslate2 still works.
> Code
> Output
> ### Similarly, pyannote.audio works if used alone
> Code
> Output
> ### However, if CTranslate2 is used beforehand, pyannote.audio stucks at pipeline.to(torch.device("cuda")) (RuntimeError: cuDNN error: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH)
> Code
> Output
> ### Similarly, if pyannote.audio is imported beforehand, CTranslate2 crashes.
> Code
> Output
> ### Workaround: Isolate CTranslate2 process using multiprocessing
> Code
> Output
> ### Improved workaround: Upgrading torch takes long time, so avoid unnecessary upgrading.
> Code
> Output

I'm going to try this too!
