### ISSUE TITLE
Software compatibility

### ISSUE THREAD

**Issue by adampwells** [m-bain/whisperX#1141]
I've spend a couple of days trying to get whisperx running on Unbuntu 24.04 using an NVIDIA T4 (bare metal server, not virtualised).

I installed wishperx using pipx, but got errors like this: 

`Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory`

TL;DR - you need to pin whisperx and ctranslate2 to the following version for it to work:

```
   package ctranslate2 4.4.0, installed using Python 3.12.3
    - ct2-fairseq-converter
    - ct2-marian-converter
    - ct2-openai-gpt2-converter
    - ct2-opennmt-py-converter
    - ct2-opennmt-tf-converter
    - ct2-opus-mt-converter
    - ct2-transformers-converter
   package whisperx 3.3.2, installed using Python 3.12.3
    - whisperx
```

**Comment by Luminarcy** [comment]
Didn't help for me, but i fixed it via

```
curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-cuda-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/nvidia-cuda-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /" | sudo tee /etc/apt/sources.list.d/nvidia-cuda.list
sudo apt update
sudo apt install libcudnn8 libcudnn8-dev
echo "/usr/lib/x86_64-linux-gnu" | sudo tee /etc/ld.so.conf.d/cudnn.conf
sudo ldconfig
```

and now `ldconfig -p | grep libcudnn_ops_infer` should print

```
(whisperx) ➜  ~ ldconfig -p | grep libcudnn_ops_infer                                                                           libcudnn_ops_infer.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
        libcudnn_ops_infer.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so
```

then restarted console and latest version now works

**Comment by xandark** [comment]
> ... and latest version now works

Your solution should be pinned in the front README.md because this is the only way to install `libcudnn8 libcudnn8-dev` on Ubuntu 24.04. 

The suggestion to just install `libcudnn8 libcudnn8-dev` will always fail unless one follows your instructions.

**Comment by fredericoschardong** [comment]
I went as far as formating my ubuntu 24.04 to try to fix this. After installing cudnn 9 what fixed this issue was

```
pip install ctranslate2==4.5.0 --break-system-packages
```
