### ISSUE TITLE
Garbage output when running on GPU

### ISSUE THREAD

**Issue by perdakovich** [m-bain/whisperX#1147]
Base command:
`whisperx --language en --model base --no_align --output_format txt --print_progress True --device cpu --compute_type int8 --batch_size 16 audio.wav`

Only --language and --device values were changed between runs.

### Russian on CPU:

Transcript: [0.031 --> 9.97]  карта для комфортного гейминга 4K с поддержкой трассировки лучей. Устройство поставляется фирменной коробки с яркой полиграфией. В комплекте необходимая документация и диск

### Russian on GPU:

Transcript: [0.031 --> 9.97]  С

---

### English on CPU:

Transcript: [0.031 --> 12.974]  perfect spread of Nutella. Look at that perfect
thickness, exactly matching the pattern of the bread itself as if the Nutella gods themselves had spread the Nutella on this piece of bread.

### English on GPU:
Transcript: [0.031 --> 12.974]  Thank you.

**Comment by danygbelanger** [comment]
I'm having a similar issue, but language doesn't matter. I'm trying to transcribe files in French and in English and every output is simply exclamation marks.

**Comment by semiaddict** [comment]
> I'm having a similar issue, but language doesn't matter. I'm trying to transcribe files in French and in English and every output is simply exclamation marks.

I'm also having the same issue.
Has anyone of you found a fix ?

**Comment by perdakovich** [comment]
I think I haven't found a fix

**Comment by danygbelanger** [comment]
> > I'm having a similar issue, but language doesn't matter. I'm trying to transcribe files in French and in English and every output is simply exclamation marks.
> 
> I'm also having the same issue. Has anyone of you found a fix ?

I have not either. I ended up giving up and simply using the regular version of Whisper and I'll fix my transcripts manually.

**Comment by semiaddict** [comment]
> I have not either. I ended up giving up and simply using the regular version of Whisper and I'll fix my transcripts manually.

Thanks for your replies.

@danygbelanger , are you using the regular Whisper locally as well? If so, it might be a problem in faster_whisper, which is used by whisperx.
I'll try to use it directly tomorrow to see if the issue can also be reproduced.

**Comment by danygbelanger** [comment]
> [@danygbelanger](https://github.com/danygbelanger) , are you using the regular Whisper locally as well? If so, it might be a problem in faster_whisper, which is used by whisperx.

I am using Whisper locally and I tried to use faster_whisper, but I also got issues making it unusable for some reason. Whisper takes a long time but at least it works for me.

**Comment by semiaddict** [comment]
I finally managed to get a decent output with both faster-whisper and whisperX with GPU by changing the compute_type from "float16" to "int8_float32".
I am currently using an old GeForce GTX 1660 Ti card, which might explain this behavior.

Edit: also works with compute_type "float32".

**Comment by danygbelanger** [comment]
I had given up, but decided to give it another go and trying what you recommended and managed to get Faster_whisper working that way. I ended trying WhisperX again to day and, after a couple hours of trying to fix the other issues I kept getting for some reason, I managed to get it working. I have no idea how, but I managed to do it. (I'm using a GeForce GTX 1660, though not Ti.) It's not perfect, but works well enough!

**Comment by diamond-lizard** [comment]
Only "float32" worked for me.
