### ISSUE TITLE
Upgrading ctranslate to >= 4.5.0

### ISSUE THREAD

**Issue by fhalde** [m-bain/whisperX#1158]
Hi,

We've been trying to install `whisperx==3.3.4` for a project which uses python 3.12 (though not sure if the python version is relevant), but we keep running into issues related to the missing `libcudnn_ops_infer.so.8` file, even after setting `LD_LIBRARY_PATH` to the correct directories under our `.venv` as discussed in several other issues.

We're aiming for a self-contained installation and prefer not to rely on prebuilt CUDA images with bundled libraries. Our base image is `ubuntu:25.04`

torch>=2.5.1 (which is a whisperx requirement), requires cuDNN9. However, another dependency of WhisperX, ctranslate2==4.4.0 is only compatible with cuDNN8 (as evident from `libcudnn_ops_infer.so.8`)

It turns out cuDNN9 doesn't include `libcudnn_ops_infer.so` (nowhere to be found under `.venv`).

I saw that support for cuDNN9 was added in ctranslate2==4.5.0:
https://github.com/OpenNMT/CTranslate2/releases/tag/v4.5.0

**Would it make sense to bump the minimum required version of ctranslate2 to 4.5.0 in [whisperx's pyproject.toml](https://github.com/m-bain/whisperX/blob/main/pyproject.toml#L12) to avoid this conflict? We just gave it a try and everything worked fine – but we'd like to get a second opinion**

Apologies if I'm oversimplifying. I'm still getting up to speed on how all of this fits together 😅

We use `uv` for build, we've pinned torch to `2.5.1` & ctranslate2 to `4.5.0`

---
Before switching to the base `ubuntu:25.04` image, we were using the CUDA image `nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04`, where everything seemed to work fine without any pinning/override dependencies. However, we later discovered that the base image included cuDNN8, while PyTorch was pulling in cuDNN9 and disparate systems seemingly were getting what they wanted and it all worked fine. It's unclear what the implications are for an application loading two different versions of the same shared library

BTW, forcing our project to only pull cuDNN8 (and not installing cuDNN9) was causing issues in torch

**Comment by fhalde** [comment]
@Barabazs I noticed that you had upgraded the ctranslate2 version to 4.5.0 on 3.3.2 but it never made it into version >= 3.3.3 https://github.com/m-bain/whisperX/issues/954

**Comment by mcDandy** [comment]
I have the same problem but I am using torch 2.7.1 which uses ctranslate 4.6.0

ERROR: Ignored the following versions that require a different python version: 3.3.0 Requires-Python <3.13,>=3.9; 3.3.1 Requires-Python <3.13,>=3.9; 3.3.2 Requires-Python <3.13,>=3.9; 3.3.3 Requires-Python <3.13,>=3.9; 3.3.4 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement ctranslate2==4.4.0 (from whisperx) (from versions: 4.6.0)
ERROR: No matching distribution found for ctranslate2==4.4.0

**Comment by fhalde** [comment]
We've had no issues bumping ctranslate2 to 4.5.0. We had to force upgrade depending on the packaging tool you use.

I haven't tried it with 4.6.0

**Comment by mcDandy** [comment]
Used python 3.13 😅

**Comment by jim60105** [comment]
Added relating to PR #1133 
However, it does not truly address your upgrade needs; rather, it resolves the issue of depending on two different libcudnn.  
For details, please refer to the PR description.

**Comment by fhalde** [comment]
Hi @jim60105 perhaps you know better, but why didn't you approach your PR by upgrading ctranslate2 to 4.5.0 instead? Do you see concerns?

**Comment by jim60105** [comment]
@fhalde Actually I previously had an opposite PR #1098.
(At the time I submitted, the ecosystem for version 12.8 was still unstable, which is why that PR was for version 12.6)

In addressing the dependency issue in #1126, the maintainer opted to downgrade. My new PR #1133 was simply to assist in finalizing things and essentially adhered to the maintainer's choice.

**Comment by jim60105** [comment]
I finally opened an upgrade PR #1182 because of [this 9.3 CRITICAL CVE](https://nvd.nist.gov/vuln/detail/CVE-2025-32434); stays in old version is no longer a suitable option.

**Comment by fhalde** [comment]
ah f, if we are anyway downgrading to cuda128, do we have to upgrade ctranslate2? @jim60105

**Comment by fhalde** [comment]
@jim60105 in your PR, you've mentioned cuda 12.8 must be installed before installing WhisperX.

I'm noticing that uv sync still pulls in cuda 12.9 into the .venv even though you've referenced the cu128 wheel.

Is this expected?

**Comment by jim60105** [comment]
> ah f, if we are anyway downgrading to cuda128, do we have to upgrade ctranslate2?
 
Not quite sure what you mean.
Generally speaking, you can install a version newer than 12.8, such as CUDA 12.9
Are you using 12.9? It's very new, I'm not sure how stable it is.

> I'm noticing that uv sync still pulls in cuda 12.9 into the .venv even though you've referenced the cu128 wheel.
> Is this expected?

@fhalde Nope, I need to take a look at it.
This is strange, only the cu128 is in the lock file.
https://github.com/jim60105/whisperX/blob/327fa856872c4b972e17041e147e7491ab3258b5/uv.lock#L2773-L2776

PyTorch hasn't released cu129 packages on the stable channel.  
Are you referring to something else?
https://download.pytorch.org/whl/torch/

**Comment by jim60105** [comment]
> We're aiming for a self-contained installation and prefer not to rely on prebuilt CUDA images with bundled libraries.

Oh, I just noticed this.
You can take a look at my work: https://github.com/jim60105/docker-whisperX

**Comment by fhalde** [comment]
You must be right, I am finding the versioning extremely confusing as a beginner. I could be on the wrong track entirely

So my confusion is arising from the following
https://download.pytorch.org/whl/nvidia-cudnn-cu12/ (under https://download.pytorch.org/whl/cu128)

For nvidia-cudnn-cu12, there is the lib version cu12-8.9, cu12-9.1, do they mean cu128 and cu129 or is that unrelated to cuda?

In my project for nvidia-cudnn-cu12, uv always pulls in the cu12-9.1 which has the `.so` not found issue for some reason. Maybe that version tag has nothing to do with cu128 / cu129

Please put some sense into my understanding 🤣

**Comment by fhalde** [comment]
You must be right, I am finding the versioning extremely confusing as a beginner. I could be on the wrong track entirely

So my confusion is arising from the following
https://download.pytorch.org/whl/nvidia-cudnn-cu12/ (under https://download.pytorch.org/whl/cu128)

For nvidia-cudnn-cu12, there is the lib version cu12-8.9, cu12-9.1, do they mean cu128 and cu129

In my project for nvidia-cudnn-cu12, uv always pulls in the cu12-9.1 which has the `.so` not found issue for some reason. Maybe that version tag has nothing to do with cu128 / cu129

Please put some sense into my understanding 🤣

**Comment by jim60105** [comment]
> For nvidia-cudnn-cu12, there is the lib version cu12-8.9, cu12-9.1, do they mean cu128 and cu129 or is that unrelated to cuda?

That's cuDNN v8.9 and v9.1, both for CUDA 12 (including versions 12.8 and 12.9).
cu128 = CUDA 12.8; cu129 = CUDA 12.9
You should only get cuDNN v9 now, and that's correct.

**Comment by Adheesh1107** [comment]
Hey @fhalde , in your initial post, you mentioned you had a working environment with CUDA support. Can you please share the pip freeze of your environment and your CUDA version details?

I am on a RHEL 9 machine with CUDA 12.4 version, python 3.11.9 and I've installed cuDNN 9.11.0. I couldn't get the application to work after trying out numerous whisper, torch versions.

**Comment by erklem** [comment]
> [@Barabazs](https://github.com/Barabazs) I noticed that you had upgraded the ctranslate2 version to 4.5.0 on 3.3.2 but it never made it into version >= 3.3.3 [#954](https://github.com/m-bain/whisperX/issues/954)

It is rather confusing that whisperX 3.3.2 bumped ctranslate2 to 4.5.0 (in requirements.txt), but then the pyproject.toml for whisperX 3.3.3 pins ctranslate2 to < 4.5.0. This seems to come from #1126, but without an explanation for why a downgrade was chosen instead of an upgrade.

It's annoying that I'll have to separately install cuDNN v8 to get this working on Ubuntu 24.04.

**Comment by Saicheg** [comment]
Any changes we will see this fix released this year? Is there any help needed?
