### ISSUE TITLE
kernel crash

### ISSUE THREAD

**Issue by Omal1k** [m-bain/whisperX#1186]
Kernel just crushing when I am trying to run whisperX latest version. My image is:

nvidia/cuda:11.6.1-cudnn8-runtime-ubuntu20.04

I also loaded: 

libcudnn8 libcudnn8-dev 

And it still crashing without any error. My container just crashing withour any logs. Please help me

**Comment by Omal1k** [comment]
I fixed it, just taken image with Cuda 11.8

**Comment by SzuPc** [comment]
Could you please tell me the current versions of torch, whisperx and cuda? Thank you very much

**Comment by Omal1k** [comment]
whisperx - 3.4.2
torch - 2.7.1
cuda - 11.8
libcudnn8


and my docker image looks like:

```
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    ffmpeg \
    software-properties-common \
    libcudnn8 \
    libcudnn8-dev \
    curl \
    wget \
    build-essential \
    && echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu jammy main" > /etc/apt/sources.list.d/deadsnakes-ppa.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA6932366A755776 \
    && apt-get update \
    && apt-get install -y python3.10 python3.10-venv python3.10-dev python3-pip \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 \
    && rm -rf /var/lib/apt/lists/*

```
