### ISSUE TITLE
New update failing to run completely.

### ISSUE THREAD

**Issue by OPPEYRADY** [m-bain/whisperX#967]
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)

No matter what I try, doesn't seem to recognize libcudnn anymore and crashes every single time when following the readme.

On anaconda, WSL2 python 1.10

**Comment by OPPEYRADY** [comment]
very janky but may be solvable by changing some paths...

**Comment by OPPEYRADY** [comment]
pip install ctranslate2==3.22.0 | Seems to fix it for now, other versions may work havent tested.

**Comment by j-dho** [comment]
@OPPEYRADY Having same issue here. Isn't whisperx 3.2.0 depend on ctranslate 4.2.0?

**Comment by Rana-Tigrina** [comment]
Sitll getting same error

environments/ai_venv/lib/python3.10/site-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

  warnings.warn(
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted (core dumped)

after install  ctranslate2==3.22.0 

I got this error 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
whisperx 3.2.0 requires ctranslate2==4.4.0, but you have ctranslate2 3.22.0 which is incompatible.
faster-whisper 1.1.0 requires ctranslate2<5,>=4.0, but you have ctranslate2 3.22.0 which is incompatible.

**Comment by Barabazs** [comment]
Latest whisperx version requires `ctranslate2==4.4.0` to prevent this issue. How did you install whisperx and are you installing it in a fresh environment?

**Comment by OPPEYRADY** [comment]
Installed it almost 1:1 to the page says as closely as possible, only thing I modified is I forced ctranslate to be down and it loaded and works normally for my case, reinstalled WSL2 multiple times, and even tried switching distros, very odd indeed!

**Comment by j-dho** [comment]
@Barabazs Does ctranslate2==4.4.0 prevent this issue? I think it is rather creating an issue..

I am using python 3.11.9 and cuda ver.12.6

Any possible solutions for this?

**Comment by Barabazs** [comment]
> Installed it almost 1:1 to the page says as closely as possible, only thing I modified is I forced ctranslate to be down and it loaded and works normally for my case, reinstalled WSL2 multiple times, and even tried switching distros, very odd indeed!
> 
> As for warnings, I ignored them and it still worked, albeit it annoying.
> 
> conda install pytorch==2.3.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> is also what I used as well that may differ from the default.

Can you try reinstalling whisperx in a clean environment and post the output of `pip list` please? If you'd rather not because it's working now, then no worries though.

**Comment by OPPEYRADY** [comment]
> > Installed it almost 1:1 to the page says as closely as possible, only thing I modified is I forced ctranslate to be down and it loaded and works normally for my case, reinstalled WSL2 multiple times, and even tried switching distros, very odd indeed!
> > As for warnings, I ignored them and it still worked, albeit it annoying.
> > conda install pytorch==2.3.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> > is also what I used as well that may differ from the default.
> 
> Can you try reinstalling whisperx in a clean environment and post the output of `pip list` please? If you'd rather not because it's working now, then no worries though.

Sure thing, I created a dummy environment and followed the readme


Package                  Version
------------------------ ------------
aiohappyeyeballs         2.4.4
aiohttp                  3.11.11
aiosignal                1.3.2
alembic                  1.14.0
antlr4-python3-runtime   4.9.3
asteroid-filterbanks     0.4.0
async-timeout            5.0.1
attrs                    24.3.0
audioread                3.0.1
av                       11.0.0
certifi                  2024.12.14
cffi                     1.17.1
charset-normalizer       3.4.1
click                    8.1.8
coloredlogs              15.0.1
colorlog                 6.9.0
contourpy                1.3.1
ctranslate2              4.4.0
cycler                   0.12.1
Cython                   3.0.0
decorator                5.1.1
docopt                   0.6.2
einops                   0.8.0
faster-whisper           1.0.0
filelock                 3.13.1
flatbuffers              24.12.23
fonttools                4.55.3
frozenlist               1.5.0
fsspec                   2024.12.0
gmpy2                    2.1.2
greenlet                 3.1.1
huggingface-hub          0.27.0
humanfriendly            10.0
HyperPyYAML              1.2.2
idna                     3.10
Jinja2                   3.1.4
joblib                   1.4.2
julius                   0.2.7
kiwisolver               1.4.8
lazy_loader              0.4
librosa                  0.10.2.post1
lightning                2.5.0.post0
lightning-utilities      0.11.9
llvmlite                 0.43.0
Mako                     1.3.8
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.10.0
mdurl                    0.1.2
mpmath                   1.3.0
msgpack                  1.1.0
multidict                6.1.0
networkx                 3.3
nltk                     3.9.1
numba                    0.60.0
numpy                    1.26.4
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
omegaconf                2.3.0
onnxruntime              1.20.1
optuna                   4.1.0
packaging                24.2
pandas                   2.2.3
pillow                   11.1.0
pip                      24.3.1
platformdirs             4.3.6
pooch                    1.8.2
primePy                  1.3
propcache                0.2.1
protobuf                 5.29.2
pyannote.audio           3.1.1
pyannote.core            5.0.0
pyannote.database        5.1.0
pyannote.metrics         3.2.1
pyannote.pipeline        3.0.1
pycparser                2.22
Pygments                 2.18.0
pyparsing                3.2.1
python-dateutil          2.9.0.post0
pytorch-lightning        2.5.0.post0
pytorch-metric-learning  2.8.1
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
ruamel.yaml              0.18.7
ruamel.yaml.clib         0.2.12
safetensors              0.4.5
scikit-learn             1.6.0
scipy                    1.14.1
semver                   3.0.2
sentencepiece            0.2.0
setuptools               75.6.0
shellingham              1.5.4
six                      1.17.0
sortedcontainers         2.4.0
soundfile                0.12.1
soxr                     0.5.0.post1
speechbrain              1.0.2
SQLAlchemy               2.0.36
sympy                    1.13.1
tabulate                 0.9.0
tensorboardX             2.6.2.2
threadpoolctl            3.5.0
tokenizers               0.15.2
torch                    2.5.1
torch-audiomentations    0.11.1
torch_pitch_shift        1.2.5
torchaudio               2.0.0
torchmetrics             1.6.1
tqdm                     4.67.1
transformers             4.39.3
triton                   3.1.0
typer                    0.15.1
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.3.0
wheel                    0.45.1
whisperx                 3.2.0
yarl                     1.18.3

**Comment by Barabazs** [comment]
> @Barabazs Does ctranslate2==4.4.0 prevent this issue?

Yes, see: https://github.com/SYSTRAN/faster-whisper/issues/729

There are also a bunch of other troubleshooting steps you can try from that issue thread.

Perhaps loosening the restriction might help too. In a fresh environment, try: `pip install "git+https://github.com/Barabazs/whisperX.git@0cb10992e4777ad5a6a0d2bc4934f53226c5032d#egg=whisperX"`

Please report back if it works and if not, post the console output of the installation.

**Comment by Barabazs** [comment]
> Sure thing, I created a dummy environment and followed the readme
> 
> This one is for pip install whisperx, should I do the development branch?

Yes, try installing from the repo directly please. And if you have some time, also try my suggestion to install `pip install "git+https://github.com/Barabazs/whisperX.git@0cb10992e4777ad5a6a0d2bc4934f53226c5032d#egg=whisperX"` which loosens the restriction for ctranslate2

**Comment by OPPEYRADY** [comment]
> > Sure thing, I created a dummy environment and followed the readme
> > This one is for pip install whisperx, should I do the development branch?
> 
> Yes, try installing from the repo directly please. And if you have some time, also try my suggestion to install `pip install "git+https://github.com/Barabazs/whisperX.git@0cb10992e4777ad5a6a0d2bc4934f53226c5032d#egg=whisperX"` which loosens the restriction for ctranslate2

Package                  Version (Development Branch)
------------------------ ------------
aiohappyeyeballs         2.4.4
aiohttp                  3.11.11
aiosignal                1.3.2
alembic                  1.14.0
antlr4-python3-runtime   4.9.3
asteroid-filterbanks     0.4.0
async-timeout            5.0.1
attrs                    24.3.0
audioread                3.0.1
av                       14.0.1
certifi                  2024.12.14
cffi                     1.17.1
charset-normalizer       3.4.1
click                    8.1.8
coloredlogs              15.0.1
colorlog                 6.9.0
contourpy                1.3.1
ctranslate2              4.4.0
cycler                   0.12.1
decorator                5.1.1
docopt                   0.6.2
einops                   0.8.0
faster-whisper           1.1.0
filelock                 3.13.1
flatbuffers              24.12.23
fonttools                4.55.3
frozenlist               1.5.0
fsspec                   2024.12.0
gmpy2                    2.1.2
greenlet                 3.1.1
huggingface-hub          0.27.0
humanfriendly            10.0
HyperPyYAML              1.2.2
idna                     3.10
Jinja2                   3.1.4
joblib                   1.4.2
julius                   0.2.7
kiwisolver               1.4.8
lazy_loader              0.4
librosa                  0.10.2.post1
lightning                2.5.0.post0
lightning-utilities      0.11.9
llvmlite                 0.43.0
Mako                     1.3.8
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.10.0
mdurl                    0.1.2
mkl_fft                  1.3.11
mkl_random               1.2.8
mkl-service              2.4.0
mpmath                   1.3.0
msgpack                  1.1.0
multidict                6.1.0
networkx                 3.2.1
nltk                     3.9.1
numba                    0.60.0
numpy                    2.0.1
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
omegaconf                2.3.0
onnxruntime              1.20.1
optuna                   4.1.0
packaging                24.2
pandas                   2.2.3
pillow                   11.1.0
pip                      24.2
platformdirs             4.3.6
pooch                    1.8.2
primePy                  1.3
propcache                0.2.1
protobuf                 5.29.2
pyannote.audio           3.3.2
pyannote.core            5.0.0
pyannote.database        5.1.0
pyannote.metrics         3.2.1
pyannote.pipeline        3.0.1
pycparser                2.22
Pygments                 2.18.0
pyparsing                3.2.1
python-dateutil          2.9.0.post0
pytorch-lightning        2.5.0.post0
pytorch-metric-learning  2.8.1
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
ruamel.yaml              0.18.7
ruamel.yaml.clib         0.2.12
safetensors              0.4.5
scikit-learn             1.6.0
scipy                    1.14.1
semver                   3.0.2
sentencepiece            0.2.0
setuptools               75.1.0
shellingham              1.5.4
six                      1.17.0
sortedcontainers         2.4.0
soundfile                0.12.1
soxr                     0.5.0.post1
speechbrain              1.0.2
SQLAlchemy               2.0.36
sympy                    1.13.1
tabulate                 0.9.0
tensorboardX             2.6.2.2
threadpoolctl            3.5.0
tokenizers               0.21.0
torch                    2.5.1
torch-audiomentations    0.11.1
torch_pitch_shift        1.2.5
torchaudio               2.5.1
torchmetrics             1.6.1
tqdm                     4.67.1
transformers             4.47.1
triton                   3.1.0
typer                    0.15.1
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.3.0
wheel                    0.44.0
whisperx                 3.2.0
yarl                     1.18.3

**Comment by OPPEYRADY** [comment]
> > Sure thing, I created a dummy environment and followed the readme
> > This one is for pip install whisperx, should I do the development branch?
> 
> Yes, try installing from the repo directly please. And if you have some time, also try my suggestion to install `pip install "git+https://github.com/Barabazs/whisperX.git@0cb10992e4777ad5a6a0d2bc4934f53226c5032d#egg=whisperX"` which loosens the restriction for ctranslate2


TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

  warnings.warn(
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)

Error has not changed it seems.


Package                  Version (Your Version)
------------------------ ------------
aiohappyeyeballs         2.4.4
aiohttp                  3.11.11
aiosignal                1.3.2
alembic                  1.14.0
antlr4-python3-runtime   4.9.3
asteroid-filterbanks     0.4.0
async-timeout            5.0.1
attrs                    24.3.0
audioread                3.0.1
av                       14.0.1
certifi                  2024.12.14
cffi                     1.17.1
charset-normalizer       3.4.1
click                    8.1.8
coloredlogs              15.0.1
colorlog                 6.9.0
contourpy                1.3.1
ctranslate2              4.4.0
cycler                   0.12.1
decorator                5.1.1
docopt                   0.6.2
einops                   0.8.0
faster-whisper           1.1.0
filelock                 3.13.1
flatbuffers              24.12.23
fonttools                4.55.3
frozenlist               1.5.0
fsspec                   2024.12.0
gmpy2                    2.1.2
greenlet                 3.1.1
huggingface-hub          0.27.0
humanfriendly            10.0
HyperPyYAML              1.2.2
idna                     3.10
Jinja2                   3.1.4
joblib                   1.4.2
julius                   0.2.7
kiwisolver               1.4.8
lazy_loader              0.4
librosa                  0.10.2.post1
lightning                2.5.0.post0
lightning-utilities      0.11.9
llvmlite                 0.43.0
Mako                     1.3.8
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.10.0
mdurl                    0.1.2
mkl_fft                  1.3.11
mkl_random               1.2.8
mkl-service              2.4.0
mpmath                   1.3.0
msgpack                  1.1.0
multidict                6.1.0
networkx                 3.2.1
nltk                     3.9.1
numba                    0.60.0
numpy                    2.0.1
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
omegaconf                2.3.0
onnxruntime              1.20.1
optuna                   4.1.0
packaging                24.2
pandas                   2.2.3
pillow                   11.1.0
pip                      24.2
platformdirs             4.3.6
pooch                    1.8.2
primePy                  1.3
propcache                0.2.1
protobuf                 5.29.2
pyannote.audio           3.3.2
pyannote.core            5.0.0
pyannote.database        5.1.0
pyannote.metrics         3.2.1
pyannote.pipeline        3.0.1
pycparser                2.22
Pygments                 2.18.0
pyparsing                3.2.1
python-dateutil          2.9.0.post0
pytorch-lightning        2.5.0.post0
pytorch-metric-learning  2.8.1
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
ruamel.yaml              0.18.7
ruamel.yaml.clib         0.2.12
safetensors              0.4.5
scikit-learn             1.6.0
scipy                    1.14.1
semver                   3.0.2
sentencepiece            0.2.0
setuptools               75.1.0
shellingham              1.5.4
six                      1.17.0
sortedcontainers         2.4.0
soundfile                0.12.1
soxr                     0.5.0.post1
speechbrain              1.0.2
SQLAlchemy               2.0.36
sympy                    1.13.1
tabulate                 0.9.0
tensorboardX             2.6.2.2
threadpoolctl            3.5.0
tokenizers               0.21.0
torch                    2.5.1
torch-audiomentations    0.11.1
torch_pitch_shift        1.2.5
torchaudio               2.5.1
torchmetrics             1.6.1
tqdm                     4.67.1
transformers             4.47.1
triton                   3.1.0
typer                    0.15.1
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.3.0
wheel                    0.44.0
whisperx                 3.2.0
yarl                     1.18.3

**Comment by OPPEYRADY** [comment]
If needed, I can show one that does for some reason work, and its pip list.

**Comment by Barabazs** [comment]
> If needed, I can show one that does for some reason work, and its pip list.

Yes that could be helpful, thanks! It's a weird dependency issue, and seems to only apply to some configurations... 

For those that still have issues, there are also successful workaround described here: https://github.com/SYSTRAN/faster-whisper/issues/516

**Comment by OPPEYRADY** [comment]
> > If needed, I can show one that does for some reason work, and its pip list.
> 
> Yes that could be helpful, thanks! It's a weird dependency issue, and seems to only apply to some configurations...
> 
> For those that still have issues, there are also successful workaround described here: [SYSTRAN/faster-whisper#516](https://github.com/SYSTRAN/faster-whisper/issues/516)

(WORKS ON MY SYSTEM)


(yaml)
name: transcription
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cython=3.0.0

conda env create -f ./yaml/transcriptionwsl2.yaml
conda activate transcription
# Changed pytorch versions
conda install pytorch==2.3.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
conda install -c conda-forge ffmpeg
pip install git+https://github.com/m-bain/whisperx.git
# This is just for my server lel
pip install flask==3.0.3 #
pip install waitress==3.0.0
pip install Flask-Caching==2.3.0
# This is where I hot replace ctranslate and it corrects the lib error for some reason?
pip install ctranslate2==3.22.0

Package                 Version
----------------------- ------------
aiohappyeyeballs        2.4.4
aiohttp                 3.11.11
aiosignal               1.3.2
alembic                 1.14.0
antlr4-python3-runtime  4.9.3
asteroid-filterbanks    0.4.0
async-timeout           5.0.1
attrs                   24.3.0
audioread               3.0.1
av                      14.0.1
blinker                 1.9.0
cachelib                0.9.0
certifi                 2024.12.14
cffi                    1.17.1
charset-normalizer      3.4.1
click                   8.1.8
coloredlogs             15.0.1
colorlog                6.9.0
contourpy               1.3.1
ctranslate2             3.22.0
cycler                  0.12.1
Cython                  3.0.0
decorator               5.1.1
docopt                  0.6.2
einops                  0.8.0
faster-whisper          1.1.0
filelock                3.13.1
Flask                   3.0.3
Flask-Caching           2.3.0
flatbuffers             24.12.23
fonttools               4.55.3
frozenlist              1.5.0
fsspec                  2024.12.0
gmpy2                   2.1.2
greenlet                3.1.1
huggingface-hub         0.27.0
humanfriendly           10.0
HyperPyYAML             1.2.2
idna                    3.10
itsdangerous            2.2.0
Jinja2                  3.1.4
joblib                  1.4.2
julius                  0.2.7
kiwisolver              1.4.8
lazy_loader             0.4
librosa                 0.10.2.post1
lightning               2.5.0.post0
lightning-utilities     0.11.9
llvmlite                0.43.0
Mako                    1.3.8
markdown-it-py          3.0.0
MarkupSafe              2.1.3
matplotlib              3.10.0
mdurl                   0.1.2
mpmath                  1.3.0
msgpack                 1.1.0
multidict               6.1.0
networkx                3.3
nltk                    3.9.1
numba                   0.60.0
numpy                   1.26.4
omegaconf               2.3.0
onnxruntime             1.20.1
optuna                  4.1.0
packaging               24.2
pandas                  2.2.3
pillow                  11.1.0
pip                     24.3.1
platformdirs            4.3.6
pooch                   1.8.2
primePy                 1.3
propcache               0.2.1
protobuf                5.29.2
pyannote.audio          3.3.2
pyannote.core           5.0.0
pyannote.database       5.1.0
pyannote.metrics        3.2.1
pyannote.pipeline       3.0.1
pycparser               2.22
Pygments                2.18.0
pyparsing               3.2.1
python-dateutil         2.9.0.post0
pytorch-lightning       2.5.0.post0
pytorch-metric-learning 2.8.1
pytz                    2024.2
PyYAML                  6.0.2
regex                   2024.11.6
requests                2.32.3
rich                    13.9.4
ruamel.yaml             0.18.7
ruamel.yaml.clib        0.2.12
safetensors             0.4.5
scikit-learn            1.6.0
scipy                   1.14.1
semver                  3.0.2
sentencepiece           0.2.0
setuptools              75.6.0
shellingham             1.5.4
six                     1.17.0
sortedcontainers        2.4.0
soundfile               0.12.1
soxr                    0.5.0.post1
speechbrain             1.0.2
SQLAlchemy              2.0.36
sympy                   1.13.3
tabulate                0.9.0
tensorboardX            2.6.2.2
threadpoolctl           3.5.0
tokenizers              0.21.0
torch                   2.3.1
torch-audiomentations   0.11.1
torch_pitch_shift       1.2.5
torchaudio              2.3.1
torchmetrics            1.6.1
tqdm                    4.67.1
transformers            4.47.1
triton                  2.3.1
typer                   0.15.1
typing_extensions       4.12.2
tzdata                  2024.2
urllib3                 2.3.0
waitress                3.0.0
Werkzeug                3.1.3
wheel                   0.45.1
whisperx                3.2.0
yarl                    1.18.3

**Comment by Rana-Tigrina** [comment]
Thanks, the issue got resolved. @OPPEYRADY 

Whisperx was working fine for me , but when i cloned my project to new system and installed requirements , it was giving me that error (Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory , Aborted (core dumped) ). I tried everything it was not able to get it working.

I followed you instructions and its working fine now.

1. python3.10 -m venv myenv

2. pip install torch==2.3.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

(earlier i was doing 
pip install torch==2.0.0 torchaudio==2.0.0 --index-url https://download.pytorch.org/whl/cu118)

3.pip install imageio[ffmpeg]
(i  did'nt need it but installed it as you said)

4. pip install git+https://github.com/m-bain/whisperx.git

5. pip install -r requiremnts.txt
(my other requiremnts for my project)

i didnt do pip install ctranslate2==3.22.0, its working fine without it.



My pip list 

Package                      Version
---------------------------- ------------
aiohappyeyeballs             2.4.4
aiohttp                      3.11.11
aiosignal                    1.3.2
alembic                      1.14.0
annotated-types              0.7.0
antlr4-python3-runtime       4.9.3
asteroid-filterbanks         0.4.0
async-timeout                5.0.1
attrs                        24.3.0
audioread                    3.0.1
av                           14.0.1
blinker                      1.9.0
blis                         1.1.0
cachetools                   5.5.0
catalogue                    2.0.10
certifi                      2024.12.14
cffi                         1.17.1
charset-normalizer           3.4.1
click                        8.1.8
cloudpathlib                 0.20.0
coloredlogs                  15.0.1
colorlog                     6.9.0
confection                   0.1.5
contourpy                    1.3.1
ctranslate2                  4.4.0
cycler                       0.12.1
cymem                        2.0.10
decorator                    5.1.1
docopt                       0.6.2
einops                       0.8.0
faster-whisper               1.1.0
ffmpeg-python                0.2.0
filelock                     3.13.1
Flask                        3.1.0
flatbuffers                  24.12.23
fonttools                    4.55.3
frozenlist                   1.5.0
fsspec                       2024.2.0
future                       1.0.0
google-ai-generativelanguage 0.6.10
google-api-core              2.24.0
google-api-python-client     2.156.0
google-auth                  2.37.0
google-auth-httplib2         0.2.0
google-generativeai          0.8.3
googleapis-common-protos     1.66.0
greenlet                     3.1.1
grpcio                       1.68.1
grpcio-status                1.68.1
httplib2                     0.22.0
huggingface-hub              0.27.0
humanfriendly                10.0
HyperPyYAML                  1.2.2
idna                         3.10
imageio                      2.36.1
imageio-ffmpeg               0.5.1
itsdangerous                 2.2.0
Jinja2                       3.1.3
joblib                       1.4.2
julius                       0.2.7
kiwisolver                   1.4.8
langcodes                    3.5.0
language_data                1.3.0
lazy_loader                  0.4
librosa                      0.10.2.post1
lightning                    2.5.0.post0
lightning-utilities          0.11.9
llvmlite                     0.43.0
lxml                         5.3.0
Mako                         1.3.8
marisa-trie                  1.2.1
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.10.0
mdurl                        0.1.2
mpmath                       1.3.0
msgpack                      1.1.0
multidict                    6.1.0
murmurhash                   1.0.11
networkx                     3.2.1
nltk                         3.9.1
noisereduce                  3.0.3
numba                        0.60.0
numpy                        2.0.2
nvidia-cublas-cu11           11.11.3.6
nvidia-cuda-cupti-cu11       11.8.87
nvidia-cuda-nvrtc-cu11       11.8.89
nvidia-cuda-runtime-cu11     11.8.89
nvidia-cudnn-cu11            8.7.0.84
nvidia-cufft-cu11            10.9.0.58
nvidia-curand-cu11           10.3.0.86
nvidia-cusolver-cu11         11.4.1.48
nvidia-cusparse-cu11         11.7.5.86
nvidia-nccl-cu11             2.20.5
nvidia-nvtx-cu11             11.8.86
omegaconf                    2.3.0
onnxruntime                  1.20.1
optuna                       4.1.0
packaging                    24.2
pandas                       2.2.3
pillow                       11.1.0
pip                          22.0.2
platformdirs                 4.3.6
pooch                        1.8.2
preshed                      3.0.9
primePy                      1.3
propcache                    0.2.1
proto-plus                   1.25.0
protobuf                     5.29.2
psutil                       6.1.1
pyannote.audio               3.3.2
pyannote.core                5.0.0
pyannote.database            5.1.0
pyannote.metrics             3.2.1
pyannote.pipeline            3.0.1
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pycparser                    2.22
pydantic                     2.10.4
pydantic_core                2.27.2
pydub                        0.25.1
Pygments                     2.18.0
pyparsing                    3.2.1
python-dateutil              2.9.0.post0
python-docx                  1.1.2
python-dotenv                1.0.1
pytorch-lightning            2.5.0.post0
pytorch-metric-learning      2.8.1
pytz                         2024.2
PyYAML                       6.0.2
regex                        2024.11.6
requests                     2.32.3
rich                         13.9.4
rsa                          4.9
ruamel.yaml                  0.18.8
ruamel.yaml.clib             0.2.12
safetensors                  0.4.5
scikit-learn                 1.6.0
scipy                        1.14.1
semver                       3.0.2
sentencepiece                0.2.0
setuptools                   75.6.0
shellingham                  1.5.4
six                          1.17.0
smart-open                   7.1.0
sortedcontainers             2.4.0
soundfile                    0.12.1
soxr                         0.5.0.post1
spacy                        3.8.3
spacy-legacy                 3.0.12
spacy-loggers                1.0.5
speechbrain                  1.0.2
SpeechRecognition            3.13.0
SQLAlchemy                   2.0.36
srsly                        2.5.0
sympy                        1.13.1
tabulate                     0.9.0
tensorboardX                 2.6.2.2
thinc                        8.3.3
threadpoolctl                3.5.0
tokenizers                   0.21.0
torch                        2.3.1+cu118
torch-audiomentations        0.11.1
torch_pitch_shift            1.2.5
torchaudio                   2.3.1+cu118
torchmetrics                 1.6.1
tqdm                         4.67.1
transformers                 4.47.1
triton                       2.3.1
typer                        0.15.1
typing_extensions            4.12.2
tzdata                       2024.2
uritemplate                  4.1.1
urllib3                      2.3.0
wasabi                       1.1.3
weasel                       0.4.1
Werkzeug                     3.1.3
whisperx                     3.2.0
wrapt                        1.17.0
yarl                         1.18.3

**Comment by Vaviloff** [comment]
Thanks @Rana-Tigrina, this has worked for me today on Ubuntu 24 with Python 3.12 and CUDA 12.6:

```sh
python3 -m venv whisperx && cd whisperx
./bin/pip install torch==2.3.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
./bin/pip install git+https://github.com/m-bain/whisperx.git
```

**Comment by iamashwin99** [comment]
For those getting this error on Google colab, forcing `CTranslate2==4.5.0` at the moment seems to work. See:
https://github.com/SYSTRAN/faster-whisper/issues/1236

**Comment by subnormalmatrix** [comment]
faced this same issue while building with docker. Here's my dockerfile for reference, hopefully it helps someone

```
FROM --platform=linux/amd64 python:3.12.3

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y ffmpeg wget

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb \
    && dpkg -i cuda-keyring_1.0-1_all.deb \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y libcudnn8 libcudnn8-dev

RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt

CMD ["python", "asr.py"]
```
and the requirments file for reference
boto3==1.36.20
ffmpeg-python==0.2.0
python-dotenv==1.0.1
whisperx==3.3.1


credit: https://github.com/SYSTRAN/faster-whisper/issues/729#issuecomment-1982898317

**Comment by minhtien020900** [comment]
I recently ran into this issue when installing whisperx. After some trial and error, here are the options I tried — and they worked for me:

✅ **Option 1:** Upgrade ctranslate2 to version 4.5.0. This version fixes compatibility with newer CUDA/cuDNN versions. You can find the explanation in this related issue [#1158](https://github.com/m-bain/whisperX/issues/1158)
> pip install ctranslate2==4.5.0

📌**Note:** You might see some warning messages during installation — just ignore them, everything should still work.

✅ **Option 2:** Follow the suggestion from @Vaviloff. Thank you very much 💕 
✅ **Option 3:** Install inside a virtual environment (venv) on Linux (I’m using Ubuntu 20.04). I followed the guide from [faster-whisper](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#install-with-pip-linux-only) and made a small change:
> pip install nvidia-cublas-**cu12** nvidia-cudnn-**cu12**==**8.***

📌**Note:** You need to check your actual CUDA version before using **cu12**. Run:
> nvidia-smi
nvcc --version

Then replace **cu12** in the pip command with the correct version (e.g. cu11, cu10, etc.) based on what `nvcc --version` returns.

🔧 If you still get errors like: `Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}
` Then try running this command: 

> export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib/python3.x/site-packages/nvidia/cublas/lib:$VIRTUAL_ENV/lib/python3.x/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH"

The same applies to python3.x, where the x must be substituted with the Python version in use. Remember, this export only works in the current terminal session. To make it permanent, you can add it to your `~/.bashrc` file.

**Comment by bisonbet** [comment]
The ctranslate update worked for me!  Thanks for updating here.

**Comment by d-shehu** [comment]
Thanks to subnormalmatrix's workaround, I got past it. But there are still mismatches with deps. I'm using Ubuntu 24.04 and so it seems is the pytorch docker image for 12.6. See below.

Initially tried installing whisperx from github. However, I had to install the pip package to get it working without errors: https://pypi.org/project/whisperx

I always install in a free virtual env (dir) within a Docker image I (re)build by inheriting from the image below. It's a clean image with no other packages/dependencies.

pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime

Pip list:
`
ctranslate2                       4.4.0
numpy                               2.3.1
pytorch-lightning             2.5.2
pytorch-metric-learning  2.8.1
torch                                  2.7.1
torch-audiomentations    0.12.0
torch_pitch_shift              1.2.5
torchaudio                         2.7.1
torchmetrics                     1.8.0
torchvision                        0.22.1
whisperx                           3.4.2
`

If some has a nicer/simpler way to install on ubuntu 24.04, I'd appreciate it. I still get this warning which I didn't see before. And yes, I'm doing this exactly python before loading the models and transcribing, etc. Thanks.

`
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
`

**Comment by jim60105** [comment]
> pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime

@d-shehu Since you are on torch 2.7.1, take a look at this PR #1182  
This PR completely resolves the dependency issue.

---

Furthermore, if anyone is looking to write the Dockerfile for whisperX, feel free to check out my work.  
I assure you will find plenty of inspiration.  
https://github.com/jim60105/docker-whisperX/blob/master/Dockerfile

**Comment by thesilentg** [comment]
Thanks for all the work on this library. Appreciate it!

I'd also would like to express a preference for upgrading this library to support cuDNN9 if possible (ctranslate2 >= 4.5.0). The AWS PyTorch Deep learning containers seem to [only support](https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/appendix-dlc-release-notes-pytorch.html) CUDDA 12 / cuDNN9 at this point, [as do](https://docs.aws.amazon.com/dlami/latest/devguide/pytorch-ami.html) the AWS Deep learning AMIs.

**Comment by jim60105** [comment]
> I'd also would like to express a preference for upgrading this library to support cuDNN9 if possible (ctranslate2 >= 4.5.0). The AWS PyTorch Deep learning containers seem to [only support](https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/appendix-dlc-release-notes-pytorch.html) CUDDA 12 / cuDNN9 at this point, [as do](https://docs.aws.amazon.com/dlami/latest/devguide/pytorch-ami.html) the AWS Deep learning AMIs.
 
@thesilentg This is a closed issue, leaving a comment on PR #1182 would make it easier to gain attention.😉
